2019-04-16 09:01:58.712 [error] <0.445.0> Supervisor 'Elixir.Logger.Supervisor' had child 'Elixir.Logger.ErrorHandler' started with 'Elixir.Logger.Watcher':start_link({error_logger,'Elixir.Logger.ErrorHandler',{true,false,500}}) at <0.450.0> exit with reason normal in context child_terminated
2019-04-18 21:31:11.791 [error] <0.359.0> Supervisor 'Elixir.Logger.Supervisor' had child 'Elixir.Logger.ErrorHandler' started with 'Elixir.Logger.Watcher':start_link({error_logger,'Elixir.Logger.ErrorHandler',{true,false,500}}) at <0.364.0> exit with reason normal in context child_terminated
2019-04-18 21:34:15.048 [error] <0.146.0> Supervisor 'Elixir.Logger.Supervisor' had child 'Elixir.Logger.ErrorHandler' started with 'Elixir.Logger.Watcher':start_link({error_logger,'Elixir.Logger.ErrorHandler',{true,false,500}}) at <0.151.0> exit with reason normal in context child_terminated
2019-04-18 21:35:01.653 [error] <0.155.0> Supervisor 'Elixir.Logger.Supervisor' had child 'Elixir.Logger.ErrorHandler' started with 'Elixir.Logger.Watcher':start_link({error_logger,'Elixir.Logger.ErrorHandler',{true,false,500}}) at <0.160.0> exit with reason normal in context child_terminated
2019-04-18 21:48:00.676 [error] <0.167.0> Supervisor 'Elixir.Logger.Supervisor' had child 'Elixir.Logger.ErrorHandler' started with 'Elixir.Logger.Watcher':start_link({error_logger,'Elixir.Logger.ErrorHandler',{true,false,500}}) at <0.172.0> exit with reason normal in context child_terminated
2019-04-18 21:48:00.859 [error] <0.247.0> gen_server <0.247.0> terminated with reason: "stopping because dependent process <0.244.0> died: shutdown"
2019-04-18 21:48:00.859 [error] <0.247.0> CRASH REPORT Process <0.247.0> with 0 neighbours exited with reason: "stopping because dependent process <0.244.0> died: shutdown" in gen_server:handle_common_reply/8 line 726
2019-04-18 21:48:17.385 [error] <0.155.0> Supervisor 'Elixir.Logger.Supervisor' had child 'Elixir.Logger.ErrorHandler' started with 'Elixir.Logger.Watcher':start_link({error_logger,'Elixir.Logger.ErrorHandler',{true,false,500}}) at <0.160.0> exit with reason normal in context child_terminated
2019-04-18 21:57:48.031 [error] <0.161.0> Supervisor 'Elixir.Logger.Supervisor' had child 'Elixir.Logger.ErrorHandler' started with 'Elixir.Logger.Watcher':start_link({error_logger,'Elixir.Logger.ErrorHandler',{true,false,500}}) at <0.166.0> exit with reason normal in context child_terminated
2019-04-18 22:00:29.135 [error] <0.172.0> Supervisor 'Elixir.Logger.Supervisor' had child 'Elixir.Logger.ErrorHandler' started with 'Elixir.Logger.Watcher':start_link({error_logger,'Elixir.Logger.ErrorHandler',{true,false,500}}) at <0.177.0> exit with reason normal in context child_terminated
2019-04-18 22:00:29.226 [error] <0.228.0> CRASH REPORT Process <0.228.0> with 0 neighbours exited with reason: #{'__exception__' => true,'__struct__' => 'Elixir.ArgumentError',message => <<"The module Broker was given as a child to a supervisor but it does not exist.">>} in 'Elixir.Supervisor':init_child/1 line 629 in application_master:init/4 line 134
2019-04-18 22:00:56.423 [error] <0.172.0> Supervisor 'Elixir.Logger.Supervisor' had child 'Elixir.Logger.ErrorHandler' started with 'Elixir.Logger.Watcher':start_link({error_logger,'Elixir.Logger.ErrorHandler',{true,false,500}}) at <0.177.0> exit with reason normal in context child_terminated
2019-04-18 22:02:16.615 [error] <0.160.0> Supervisor 'Elixir.Logger.Supervisor' had child 'Elixir.Logger.ErrorHandler' started with 'Elixir.Logger.Watcher':start_link({error_logger,'Elixir.Logger.ErrorHandler',{true,false,500}}) at <0.165.0> exit with reason normal in context child_terminated
2019-04-18 22:02:22.279 [error] <0.155.0> Supervisor 'Elixir.Logger.Supervisor' had child 'Elixir.Logger.ErrorHandler' started with 'Elixir.Logger.Watcher':start_link({error_logger,'Elixir.Logger.ErrorHandler',{true,false,500}}) at <0.160.0> exit with reason normal in context child_terminated
2019-04-18 22:05:59.868 [error] <0.172.0> Supervisor 'Elixir.Logger.Supervisor' had child 'Elixir.Logger.ErrorHandler' started with 'Elixir.Logger.Watcher':start_link({error_logger,'Elixir.Logger.ErrorHandler',{true,false,500}}) at <0.177.0> exit with reason normal in context child_terminated
2019-04-18 22:06:16.522 [error] <0.146.0> Supervisor 'Elixir.Logger.Supervisor' had child 'Elixir.Logger.ErrorHandler' started with 'Elixir.Logger.Watcher':start_link({error_logger,'Elixir.Logger.ErrorHandler',{true,false,500}}) at <0.151.0> exit with reason normal in context child_terminated
2019-04-18 22:06:21.677 [error] <0.146.0> Supervisor 'Elixir.Logger.Supervisor' had child 'Elixir.Logger.ErrorHandler' started with 'Elixir.Logger.Watcher':start_link({error_logger,'Elixir.Logger.ErrorHandler',{true,false,500}}) at <0.151.0> exit with reason normal in context child_terminated
